import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
        import { MovementFiltersProvider } from '@/state/MovementFiltersContext';
import { TrackerProvider } from '@/state/TrackerContext';
import { Navbar } from '@/components/Navbar';
import { ThemeProvider } from '@/state/ThemeContext';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
          <body className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen bg-gradient-to-br from-slate-100 to-slate-200 dark:from-neutral-900 dark:to-neutral-950 text-neutral-900 dark:text-neutral-50`}>
            <ThemeProvider>
              <MovementFiltersProvider>
              <TrackerProvider>
                <div className="sticky top-0 z-20 px-4 pt-4">
                  <Navbar />
                </div>
                {children}
              </TrackerProvider>
              </MovementFiltersProvider>
            </ThemeProvider>
          </body>
    </html>
  );
}
